services:
     db:
          container_name: postgres
          image: postgres:${DB_POSTGRES_VERSION}
          restart: always
          shm_size: 512m
          ports:
               - "${DB_POSTGRES_PORT}:5432"
          environment:
               POSTGRES_DB: ${DB_POSTGRES_DATABASE}
               POSTGRES_USER: ${DB_POSTGRES_USER}
               POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
               PGDATA: /var/lib/postgresql/data
          volumes:
               - db_postgres:/var/lib/postgresql/data

     pgadmin:
          image: dpage/pgadmin4:8.13
          container_name: pgadmin
          restart: always
          environment:
               PGADMIN_DEFAULT_EMAIL: ${MANAGE_PGADMIN_EMAIL}
               PGADMIN_DEFAULT_PASSWORD: ${MANAGE_PGADMIN_PASSWORD}
          ports:
               - "${MANAGE_PGADMIN_PORT_EXPOSE}:80"
          volumes:
               - ./backups:/var/lib/pgadmin/storage
volumes:
     db_postgres:
