services:
     db:
          container_name: postgres
          image: postgres:${DB_POSTGRES_VERSION}
          restart: always
          shm_size: 512m
          ports:
               - "${DB_POSTGRES_PORT}:5432"
          environment:
               POSTGRES_DB: ${DB_POSTGRES_DATABASE}
               POSTGRES_USER: ${DB_POSTGRES_USER}
               POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
               PGDATA: /var/lib/postgresql/data
          volumes:
               - db_postgres:/var/lib/postgresql/data

     admin:
          container_name: pgadmin
          image: elestio/pgadmin:REL-8_13
          restart: always
          environment:
               PGADMIN_DEFAULT_EMAIL: ${MANAGE_PGADMIN_EMAIL}
               PGADMIN_DEFAULT_PASSWORD: ${MANAGE_PGADMIN_PASSWORD}
               PGADMIN_LISTEN_PORT: 8080
          ports:
               - "${MANAGE_PGADMIN_PORT_EXPOSE}:8080"
          volumes:
               - servers:/pgadmin4

volumes:
     db_postgres:
     servers:
